# Generated by Django 5.2.1 on 2025-05-28 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequest_App', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='managerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='manager_profile_pictures/')),
                ('email', models.EmailField(default='', max_length=254)),
                ('employee_id', models.CharField(default='', max_length=20)),
                ('position_title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='request_officerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('derpartment', models.CharField(default='', max_length=100)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pictures/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('position_title', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('employee_id', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='nothing', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
