# Generated by Django 5.2.1 on 2025-06-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequest_App', '0002_managerprofile_request_officerprofile_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
    ]
