# Generated by Django 5.2.1 on 2025-06-16 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequest_App', '0003_remove_userprofile_is_verified'),
    ]

   