# Generated by Django 5.2.1 on 2025-06-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequest_App', '0005_userprofile_department_userprofile_is_manager_and_more'),
    ]

  