# Generated by Django 5.2.1 on 2025-06-18 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequest_App', '0006_remove_approval_request'),
    ]

    