# Generated by Django 5.2.1 on 2025-06-18 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequest_App', '0007_remove_approval_request_alter_auditlog_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='request',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='PurchaseRequest_App.purchaserequest'),
        ),
    ]
