# Generated by Django 5.2.1 on 2025-06-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequest_App', '0008_remove_approval_request_alter_auditlog_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='request',
        ),
    ]
